
// Objective-C API for talking to the following Go packages
//
//	github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/ios
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Dnscryptproxy_FRAMEWORK_H__
#define __Dnscryptproxy_FRAMEWORK_H__

#include "Dnscryptproxy.objc.h"
#include "Universe.objc.h"

#endif
